version: '2'
services:
  mongo-rep1:
    image: "mongo:${MONGO_VERSION}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    command:
      - mongod
      - --replSet
      - "rs0"

  mongo-rep2:
    image: "mongo:${MONGO_VERSION}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    command:
      - mongod
      - --replSet
      - "rs0"

  mongo-rep3:
    depends_on:
      - mongo-rep1
      - mongo-rep2
    image: "mongo:${MONGO_VERSION}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    volumes:
      - ./initdb.d/restaurants.json:/docker-entrypoint-initdb.d/restaurants.json:ro
      - ./initdb.d/replica_set.sh:/docker-entrypoint-initdb.d/00_replica_set.sh:ro
      - ./initdb.d/import_dummy_data.sh:/docker-entrypoint-initdb.d/10_import_dummy_data.sh:ro
    command:
      - mongod
      - --replSet
      - "rs0"
