version: '2'
services:
  mongo-rep1:
    image: "mongo:${version}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    volumes:
      - ./mongo.conf:/etc/mongo.conf:ro
    command:
      - mongod
      - --replSet
      - "rs0"
      - --config
      - /etc/mongo.conf

  mongo-rep2:
    image: "mongo:${version}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    volumes:
      - ./mongo.conf:/etc/mongo.conf:ro
    command:
      - mongod
      - --replSet
      - "rs0"
      - --config
      - /etc/mongo.conf

  mongo-rep3:
    image: "mongo:${version}"
    labels:
        com.datadoghq.sd.check.id: "mongo-dummydata"
    volumes:
      - ./mongo.conf:/etc/mongo.conf:ro
    command:
      - mongod
      - --replSet
      - "rs0"
      - --config
      - /etc/mongo.conf

  mongo-provision:
    image: "mongo:${version}"
    depends_on:
      - mongo-rep1
      - mongo-rep2
      - mongo-rep3
    volumes:
      - ./provision/:/provision/:ro
      - ../_assets/json:/_assets/json/:ro
    command:
      - /provision/replica_set.sh
