version: '2'
services:
  mongo-standalone:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${version}"
    labels:
        com.datadoghq.sd.check.id: "elasticsearch-dummydata"
    volumes:
      - ../_assets/json/restaurants.json:/docker-entrypoint-initdb.d/restaurants.json:ro
      - ../_assets/json/employees.json:/docker-entrypoint-initdb.d/employees.json:ro
      - ./provision/import_dummy_data.sh:/docker-entrypoint-initdb.d/10_import_dummy_data.sh:ro
